apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi
spec:
  selector:
    matchLabels:
      app: python-fastapi
  template:
    metadata:
      labels:
        app: python-fastapi
    spec:
      containers:
      - name: python-fastapi
        image: shake551/python-local-k8s
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi
spec:
  type: LoadBalancer
  selector:
    app: python-fastapi
  ports:
  - port: 8700
    targetPort: 80
